/**:
    ros__parameters:
        # pan range in radians
        min_pan: 0.0
        max_pan: 0.0

        # tilt range in radians
        min_tilt: 0.0
        max_tilt: 0.0

        # zoom range in "x" (e.g. 1x - 24x optical zoom)
        min_zoom: 1
        max_zoom: 1

        # maximum angular velocity, rad/s
        max_pan_speed: 0.0
        max_tilt_speed: 0.0
